version: "3"

services:
  app:
    build:
      context: .
      dockerfile: "./build/Dockerfile"
    container_name: app
    ports:
      - "90:90"
    volumes:
      - ./logs:/logs
    networks:
      - app

networks:
  app:
